spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/trakkr
spring.datasource.username=trakkr
spring.datasource.password=trakkr

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true